apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8085

          env:
            - name: JWT_SECRET
              value: "com-innowise-authentication-service-secret-key"
            - name: INTERNAL_KEY
              value: "innowise-secret-internal-key"

          startupProbe:
            tcpSocket:
              port: 8085
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 5

          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3